import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/navbar";
import SearchBarSm from "@/components/common/searchBarSm";
import Hero from "@/components/hero";
import HiddenJems from "@/components/hiddenGems";
import TopCollections from "@/components/topCollections";
import Trending from "@/components/trending";
import Info from "@/components/info";

export default function Home() {
  const [isSmallScreen, setIsSmallScreen] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      window.innerWidth < 600
        ? setIsSmallScreen(true)
        : setIsSmallScreen(false);
    };

    handleResize();
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative sm:block text-gray-300 flex flex-col">
        <Navbar setScreen={isSmallScreen} />
        {isSmallScreen && (
          <div className="absolute flex flex-col items-center z-20 w-full h-full py-2 top-[0.7rem]">
            <SearchBarSm label="Search items, collections, accounts" />
          </div>
        )}
        <Hero />
        <Trending />
        <TopCollections />
        <HiddenJems />
        <Info />
      </main>
    </>
  );
}
