import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import SearchBarSm from "@/components/common/searchBarSm";

export default function Home() {
  const [isSmallScreen, setIsSmallScreen] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      window.innerWidth < 700
        ? setIsSmallScreen(true)
        : setIsSmallScreen(false);
    };

    handleResize();
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sm:block text-gray-300">
        <Navbar setScreen={isSmallScreen} />
        {isSmallScreen && (
          <SearchBarSm
            label="Seach items, collections, and accounts"
            setScreen={isSmallScreen}
          />
        )}
      </main>
    </>
  );
}
